[package]
name = "batch-code-analyzer-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[lib]
name = "batch_code_analyzer_desktop"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
batch-code-analyzer-ipc-contracts = { path = "../../../crates/ipc-contracts" }
tauri.workspace = true

[lints]
workspace = true
