[package]
name = "batch-code-analyzer-app-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
batch-code-analyzer-domain = { path = "../domain" }
batch-code-analyzer-persistence = { path = "../persistence" }
batch-code-analyzer-security-core = { path = "../security-core" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
